server:
  port: 8001


pring:
  application:
    name: activeMQ-learning

  activemq:
    broker-url: tcp://localhost:61616?jms.rmIdFromConnectionId=true
    user: admin
    password: admin
    packages:
      trust-all: true